version: '3.5'

services:
  redis:
    container_name: larry-redis
    image: redis
    ports:
      - 6379:6379
  larry:
    build: .
    environment:
      - REDIS_ADDRESS=larry-redis:6379
      - GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}
      - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
      - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
      - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
      - TWITTER_ACCESS_SECRET=${TWITTER_ACCESS_SECRET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    entrypoint: sh -c "/larry --topic golang -x 1 --safe-mode"
    depends_on:
      - redis
  # ----
    